/**
 * Compose/parse the machine-generated attribution marker wrapped around an
 * inter-agent prompt body.
 *
 * SEC-4 (fix): the old `plugins/agent-bus/prompt-compose.ts` prepended a
 * static-looking marker (`[Message from agent X via agent-bus (hop N)...] `)
 * directly in front of the raw body with no escaping. Because the body is
 * attacker-controlled (it can be anything a peer bot was told to relay), it
 * could contain text that looks like `] [Message from agent evil...]` —
 * closing the real marker early and opening a forged one, spoofing
 * attribution to a naive parser.
 *
 * The fix here is a fence with a token generated by the machine at compose
 * time (`crypto.randomUUID()`), *after* the body is already fixed. The
 * body's author cannot predict this token, so it cannot embed a matching
 * close-fence — any lookalike text in the body simply stays inert, part of
 * the body. Parsing only trusts the open fence anchored at index 0 and a
 * close fence at the very end whose token matches exactly.
 */
import { randomUUID } from "node:crypto";
import { MAX_HOP } from "@mirza-harness/shared";

export interface ParsedAgentPrompt {
  from: string;
  hop: number;
  id: string;
  body: string;
}

const OPEN_FENCE_RE = /^\[agent-bus from=(\S+) hop=(\d+) id=([0-9a-fA-F-]+)\]\n/;

function assertValidHop(hop: number): void {
  if (!Number.isInteger(hop) || hop < 0 || hop > MAX_HOP) {
    throw new RangeError(`hop must be an integer in 0..${MAX_HOP}, got ${hop}`);
  }
}

/**
 * Wrap `body` in a machine-generated fence carrying `from`/`hop` and a
 * random token. The token is chosen here, independent of `body`'s content,
 * so `body` cannot forge a matching close fence (fixes SEC-4).
 */
export function composeAgentPrompt(from: string, hop: number, body: string): string {
  assertValidHop(hop);
  const token = randomUUID();
  return `[agent-bus from=${from} hop=${hop} id=${token}]\n${body}\n[/agent-bus id=${token}]`;
}

/**
 * Reverse of `composeAgentPrompt`. Returns `null` if `text` does not start
 * with a well-formed open fence, or if the close fence at the very end does
 * not carry the exact same token as the open fence — i.e. no partial/forged
 * match is ever accepted. Also returns `null` if parsed hop is outside the
 * valid range 0..MAX_HOP.
 */
export function parseAgentPrompt(text: string): ParsedAgentPrompt | null {
  const openMatch = text.match(OPEN_FENCE_RE);
  if (!openMatch) return null;
  const [openFence, from, hopStr, token] = openMatch;

  const hop = Number(hopStr);
  // Validasi hop di dalam rentang 0..MAX_HOP; di luar rentang dianggap invalid
  if (!Number.isInteger(hop) || hop < 0 || hop > MAX_HOP) return null;

  const rest = text.slice(openFence.length);
  const closeFence = `\n[/agent-bus id=${token}]`;
  if (!rest.endsWith(closeFence)) return null;

  const body = rest.slice(0, rest.length - closeFence.length);
  return { from, hop, id: token, body };
}
